title: Risk and Reliability for Engineers
author: Robert Lanzafame
logo: figures/cover_small.png
copyright: Delft University of Technology, CC BY 4.0

# START DRAFT
html:
  comments:
    hypothesis: true
# END DRAFT

sphinx:
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/

  extra_extensions:
    - sphinx-image-inverter
  config:
    # See: https://github.com/executablebooks/jupyter-book/issues/1090
    bibtex_reference_style: author_year_round
    bibtex_default_style: myapastyle
    # This next line was from Caspar and doesn't work (see Issue 24)
    # https://gitlab.tudelft.nl/interactivetextbooks-citg/risk-and-reliability/-/issues/24
    # bibtex_reference_style: author_year

bibtex_bibfiles: 
  - _bibliography/references.bib
