title: Risk and Reliability for Engineers
author: Robert Lanzafame
logo: figures/cover_small.png
copyright: Delft University of Technology, CC BY 4.0

execute:
  execute_notebooks: "off"

launch_buttons:
  thebe: true


only_build_toc_files: true

# START DRAFT
html:
  comments:
    hypothesis: true
# END DRAFT
# bibtex: Thirza's hydrology hack (see issue)
sphinx:
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
# sphinx-thebe-lite extension
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]

  extra_extensions:
    # - sphinx_inline_tabs # broke
    # - sphinx_grasple # broke
    - sphinx.ext.imgconverter
    # - download_link_replacer # broke
    - jupyterbook_patches
  config:
    # See: https://github.com/executablebooks/jupyter-book/issues/1090
    bibtex_reference_style: author_year_round
    bibtex_default_style: myapastyle
    # This next line was from Caspar and doesn't work (see Issue 24)
    # https://gitlab.tudelft.nl/interactivetextbooks-citg/risk-and-reliability/-/issues/24
    # bibtex_reference_style: author_year

bibtex_bibfiles: 
  - _bibliography/references.bib
